### ISSUE TITLE
[QUESTION] - Specific API functions

### ISSUE THREAD

**Issue by zachthedev** [shinyquagsire23/InfiniteCampusAPI#6]
Does this API include a way to retrieve the students schedule? Including room #'s and teachers and course name? If not, could that be implemented or could I be pointed in the right direction to an API that does Thanks so much for making this API!

**Comment by fruzyna** [comment]
A list of classes can be obtained that has teacher names, I'm not sure about room numbers though. I'm also not sure if any order can be obtained, some of this stuff may vary by school. If you look at [my fork](https://github.com/mail929/Material-Campus) we have extended the API for use in our Android app, for access to more of the data. Somewhere in there there is a link that when the student username and password are entered in the URL a huge lump of data can be obtained. We found most of our data by manually browsing that data and figuring out how to parse it in code.

**Comment by zachthedev** [comment]
@mail929 Sorry, I haven't really worked with APIs yet. Just starting to learn. I understand how they work, but don't know syntax and setting them up yet. Would I be able to use that API for a website? I am looking at pulling schedule data from students profiles and making a live schedule feature that tells the student what class to be in and such. Thanks for the help!

**Comment by fruzyna** [comment]
Yes as long as you can fetch remote data and parse strings, which javascript is more than capable of, you can use pretty much any internet based API.

**Comment by zachthedev** [comment]
Ok, sorry, but could you give me an example? Or how I should set it up?

**Comment by fruzyna** [comment]
Some examples:

https://mobile.infinitecampus.com/mobile/checkDistrict?districtCode=[districtCode] will return a plain text webpage that has basic district info including [districtURL] and [districtAppName], I believe.

[districtURL]/verify.jsp?nonBrowser=true&username=[username]&password=[password]&appName=[districtAppName] will return a large text file that contains all information about the student that we can receive, classes, grades, etc

Putting these in a browser should return a human-readable-ish file which you can use to determine how to program your application to find the data you are looking for

**Comment by zachthedev** [comment]
Thanks so much!

**Comment by KinectTheUnknown** [comment]
I'd also like to add in that if you don't know the district code, you can search for it with `https://mobile.infinitecampus.com/mobile/searchDistrict?query=[query]&state=[stateCode]`
where `query` is the name of the department/district and `state` is the two letter code of the state. It should return an array of objects
